# Generated by Django 4.2.11 on 2024-06-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('discord_bot', models.BooleanField(default=True)),
                ('discord_token', models.CharField(blank=True, max_length=256, null=True)),
                ('Only post in listed channels?', models.BooleanField(default=False)),
                ('twitch_bot', models.BooleanField(default=True)),
                ('twitch_client_id', models.CharField(blank=True, max_length=256, null=True)),
                ('twitch_client_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('twitch_access_token', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=256)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=256)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('per_user_cooldown', models.BooleanField(default=False)),
                ('cooldown', models.IntegerField(default=60, verbose_name='Cooldown in seconds')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.chatbot')),
            ],
        ),
    ]
