# Generated by Django 4.2.11 on 2024-06-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordConfig',
            fields=[
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='botmanager.chatbot')),
                ('active', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
                ('restrict_channels', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchConfig',
            fields=[
                ('bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='botmanager.chatbot')),
                ('active', models.BooleanField(default=True)),
                ('client_id', models.CharField(blank=True, max_length=256, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=256, null=True)),
                ('access_token', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchPeriodicMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('period', models.IntegerField(default=60, verbose_name='Period in seconds')),
                ('only_while_live', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.twitchconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitchCustomPeriodicMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('period', models.IntegerField(default=60, verbose_name='Period in seconds')),
                ('only_while_live', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.twitchconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitchCustomCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('per_user_cooldown', models.BooleanField(default=False)),
                ('cooldown', models.IntegerField(default=60, verbose_name='Cooldown in seconds (Twitch)')),
                ('cooldown_while_offline', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.twitchconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitchChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=256)),
                ('channel_id', models.CharField(max_length=256)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.twitchconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchBasicCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('per_user_cooldown', models.BooleanField(default=False)),
                ('cooldown', models.IntegerField(default=60, verbose_name='Cooldown in seconds (Twitch)')),
                ('cooldown_while_offline', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.twitchconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordPeriodicMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('period', models.IntegerField(default=60, verbose_name='Period in seconds')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.discordconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordCustomPeriodicMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('period', models.IntegerField(default=60, verbose_name='Period in seconds')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.discordconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordCustomCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('per_user_cooldown', models.BooleanField(default=False)),
                ('cooldown', models.IntegerField(default=60, verbose_name='Cooldown in seconds (Twitch)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.discordconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=256)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.discordconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordBasicCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=256)),
                ('output', models.CharField(blank=True, max_length=400)),
                ('per_user_cooldown', models.BooleanField(default=False)),
                ('cooldown', models.IntegerField(default=60, verbose_name='Cooldown in seconds (Twitch)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.discordconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
