# Generated by Django 4.2.11 on 2024-06-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchat',
            name='channel_name',
            field=models.CharField(default='itswill', max_length=256),
            preserve_default=False,
        ),
    ]
