# Generated by Django 4.2.11 on 2024-07-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordbasiccommand',
            name='cooldown',
            field=models.IntegerField(default=60, verbose_name='Cooldown in seconds'),
        ),
        migrations.AlterField(
            model_name='discordcustomcommand',
            name='cooldown',
            field=models.IntegerField(default=60, verbose_name='Cooldown in seconds'),
        ),
        migrations.AlterField(
            model_name='twitchbasiccommand',
            name='cooldown',
            field=models.IntegerField(default=60, verbose_name='Cooldown in seconds'),
        ),
        migrations.AlterField(
            model_name='twitchbasiccommand',
            name='cooldown_while_offline',
            field=models.IntegerField(default=60, verbose_name='Cooldown in seconds (offline)'),
        ),
        migrations.AlterField(
            model_name='twitchcustomcommand',
            name='cooldown',
            field=models.IntegerField(default=60, verbose_name='Cooldown in seconds'),
        ),
        migrations.AlterField(
            model_name='twitchcustomcommand',
            name='cooldown_while_offline',
            field=models.IntegerField(default=60, verbose_name='Cooldown in seconds (offline)'),
        ),
    ]
