# Generated by Django 4.2.11 on 2024-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0002_alter_discordbasiccommand_cooldown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordconfig',
            name='restrict_channels',
        ),
        migrations.AddField(
            model_name='discordbasiccommand',
            name='restrict_channels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discordcustomcommand',
            name='restrict_channels',
            field=models.BooleanField(default=False),
        ),
    ]
