# Generated by Django 4.2.11 on 2024-08-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0003_remove_discordconfig_restrict_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordbasiccommand',
            name='command',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='discordcustomcommand',
            name='command',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='twitchbasiccommand',
            name='command',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='twitchcustomcommand',
            name='command',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
