# Generated by Django 4.2.11 on 2024-08-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0005_alter_discordcustomperiodicmsg_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discordbasiccommand',
            name='command',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discordcustomcommand',
            name='command',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discordcustomperiodicmsg',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discordperiodicmsg',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='twitchbasiccommand',
            name='command',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='twitchcustomcommand',
            name='command',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='twitchcustomperiodicmsg',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='twitchperiodicmsg',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
