# Generated by Django 4.2.11 on 2024-08-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0006_alter_chatbot_name_alter_discordbasiccommand_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordbasiccommand',
            old_name='per_user_cooldown',
            new_name='as_reply',
        ),
        migrations.RenameField(
            model_name='discordcustomcommand',
            old_name='per_user_cooldown',
            new_name='as_reply',
        ),
        migrations.RenameField(
            model_name='twitchbasiccommand',
            old_name='per_user_cooldown',
            new_name='as_reply',
        ),
        migrations.RenameField(
            model_name='twitchcustomcommand',
            old_name='per_user_cooldown',
            new_name='as_reply',
        ),
    ]
