# Generated by Django 4.2.11 on 2024-08-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0007_rename_per_user_cooldown_discordbasiccommand_as_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(max_length=255)),
                ('credential', models.CharField(max_length=511)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botmanager.chatbot')),
            ],
        ),
    ]
