# Generated by Django 5.1.1 on 2024-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0008_extracredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordbasiccommand',
            name='match_anywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discordbasiccommand',
            name='regex_command',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discordcustomcommand',
            name='match_anywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discordcustomcommand',
            name='regex_command',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchbasiccommand',
            name='match_anywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchbasiccommand',
            name='regex_command',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchcustomcommand',
            name='match_anywhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitchcustomcommand',
            name='regex_command',
            field=models.BooleanField(default=False),
        ),
    ]
