# Generated by Django 5.2.5 on 2025-09-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0009_discordbasiccommand_match_anywhere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchconfig',
            name='owner_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='twitchconfig',
            name='user_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
