# Generated by Django 5.2.5 on 2025-09-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0010_twitchconfig_owner_id_twitchconfig_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchconfig',
            name='access_token',
        ),
    ]
