# Generated by Django 5.2.5 on 2025-10-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0011_remove_twitchconfig_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchconfig',
            name='provider',
            field=models.CharField(default='twitch', max_length=256),
        ),
    ]
